apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  labels:
    opsrc-datastore: "true"
    opsrc-provider: redhat
  name: osd-operators-registry
  namespace: openshift-operator-lifecycle-manager
spec:
  image: quay.io/openshift-sre/osd-operators-registry:master-477f255e9caf3d40b1da495862199907
  displayName: OSD Operators
  icon:
    base64data: ""
    mediatype: ""
  publisher: Red Hat
  sourceType: grpc