apiVersion: v1
kind: Namespace
metadata:
  name: openshift-dedicated-admin
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: dedicated-admin-operator
  namespace: openshift-dedicated-admin
spec:
  targetNamespaces:
  - openshift-dedicated-admin
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: dedicated-admin-operator
  namespace: openshift-dedicated-admin
spec:
  channel: TBD
  name: dedicated-admin-operator
  source: osd-operators-registry
  sourceNamespace: openshift-operator-lifecycle-manager
